# define pass logo
PASS_LOGO= ["    PPPPPPPPPP        PPP          PPPPPPP        PPPPPPP",
            "    PPPPPPPPPPP      PPPPP        PPPPPPPPPP     PPPPPPPPPP",
            "    PPP     PPPP     PPPPP       PPPP   PPPP    PPPP   PPPP",
            "    PPP      PPP    PPPPPPP      PPP     PPPP   PPP     PPPP",
            "    PPP      PPP    PPP PPP      PPP            PPP",
            "    PPP      PPP    PPP PPP      PPPP           PPPP",
            "    PPP     PPPP   PPPP PPPP      PPPPPPP        PPPPPPP",
            "    PPPPPPPPPPP    PPP   PPP        PPPPPPP        PPPPPPP",
            "    PPPPPPPPPP     PPP   PPPP          PPPPP          PPPPP",
            "    PPP           PPPPPPPPPPP            PPPP           PPPP",
            "    PPP           PPPPPPPPPPPP   PPP      PPPP  PPP      PPP",
            "    PPP           PPP     PPPPP  PPP      PPPP  PPP      PPP",
            "    PPP          PPPP      PPP   PPPP    PPPP   PPPP    PPPP",
            "    PPP          PPP       PPPP   PPPPPPPPPP     PPPPPPPPPP",
            "    PPP         PPPP       PPPP    PPPPPPP        PPPPPPP"]
# define fail logo
FAIL_LOGO = [
            " FFFFFFFFFFF     FFF        FFF   FFF",
            " FFFFFFFFFFF    FFFFF       FFF   FFF",
            " FFF            FFFFF       FFF   FFF",
            " FFF           FFFFFFF      FFF   FFF",
            " FFF           FFF FFF      FFF   FFF",
            " FFF           FFF FFF      FFF   FFF",
            " FFFFFFFFFF   FFFF FFFF     FFF   FFF",
            " FFFFFFFFFF   FFF   FFF     FFF   FFF",
            " FFF          FFF   FFFF    FFF   FFF",
            " FFF         FFFFFFFFFFF    FFF   FFF",
            " FFF         FFFFFFFFFFF    FFF   FFF",
            " FFF         FFF     FFFF   FFF   FFF",
            " FFF        FFFF      FFF   FFF   FFF",
            " FFF        FFF       FFFF  FFF   FFFFFFFFFF",
            " FFF       FFFF       FFFF  FFF   FFFFFFFFFF"]
